sta: fix build against gcc-11.2
On gcc-11.2 build fails as:

    src/main.cpp: In function 'void print_stats(Sta*)':
    src/main.cpp:91:88: error: taking address of rvalue [-fpermissive]
       91 |                         string String = static_cast<ostringstream*>( &(ostringstream() << ii->first) )-

Fix build by simplifying expression to convert to string.